import { 
  FileSpreadsheet, 
  Lightbulb, 
  AlertTriangle, 
  Rocket, 
  CheckCircle2,
  TrendingUp,
  ArrowRight,
  Download,
  Lock
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

export interface AnalysisData {
  summary: string;
  datasetInfo: string;
  insights: string[];
  warnings: { text: string; severity: 'low' | 'medium' | 'high' }[];
  opportunities: string[];
  actions: string[];
  stats: {
    rows: number;
    columns: number;
    issues: number;
  };
}

interface AnalysisResultProps {
  data: AnalysisData;
  fileName: string;
  onNewAnalysis: () => void;
  userPlan?: string;
}

const AnalysisResult = ({ data, fileName, onNewAnalysis, userPlan = "free" }: AnalysisResultProps) => {
  const { toast } = useToast();
  const canDownload = userPlan === "pro" || userPlan === "business";

  const handleDownloadPDF = () => {
    if (!canDownload) {
      toast({
        title: "Upgrade required",
        description: "PDF export is available for Pro and Business plans.",
        variant: "destructive",
      });
      return;
    }

    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = 20;

    // Helper function to add wrapped text
    const addWrappedText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
      pdf.setFontSize(fontSize);
      pdf.setFont("helvetica", isBold ? "bold" : "normal");
      const lines = pdf.splitTextToSize(text, maxWidth);
      
      lines.forEach((line: string) => {
        if (yPosition > 270) {
          pdf.addPage();
          yPosition = 20;
        }
        pdf.text(line, margin, yPosition);
        yPosition += fontSize * 0.5;
      });
      yPosition += 5;
    };

    // Title
    pdf.setFillColor(59, 130, 246);
    pdf.rect(0, 0, pageWidth, 40, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont("helvetica", "bold");
    pdf.text("SheetSage Analysis Report", margin, 28);
    
    yPosition = 50;
    pdf.setTextColor(0, 0, 0);

    // File info
    addWrappedText(`File: ${fileName}`, 14, true);
    addWrappedText(`Generated: ${new Date().toLocaleDateString()}`, 10);
    yPosition += 5;

    // Stats
    pdf.setFillColor(245, 245, 245);
    pdf.rect(margin, yPosition, maxWidth, 25, 'F');
    yPosition += 15;
    pdf.setFontSize(11);
    pdf.text(`Rows: ${data.stats.rows.toLocaleString()}  |  Columns: ${data.stats.columns}  |  Issues: ${data.stats.issues}`, margin + 5, yPosition);
    yPosition += 20;

    // Summary
    addWrappedText("📌 Summary", 16, true);
    addWrappedText(data.datasetInfo, 11);
    addWrappedText(data.summary, 11);
    yPosition += 5;

    // Key Insights
    if (data.insights.length > 0) {
      addWrappedText("🔍 Key Insights", 16, true);
      data.insights.forEach((insight, index) => {
        addWrappedText(`${index + 1}. ${insight}`, 11);
      });
      yPosition += 5;
    }

    // Warnings
    if (data.warnings.length > 0) {
      addWrappedText("⚠️ Warnings / Risks", 16, true);
      data.warnings.forEach((warning, index) => {
        addWrappedText(`${index + 1}. [${warning.severity.toUpperCase()}] ${warning.text}`, 11);
      });
      yPosition += 5;
    }

    // Opportunities
    if (data.opportunities.length > 0) {
      addWrappedText("🚀 Opportunities", 16, true);
      data.opportunities.forEach((opportunity, index) => {
        addWrappedText(`${index + 1}. ${opportunity}`, 11);
      });
      yPosition += 5;
    }

    // Recommended Actions
    if (data.actions.length > 0) {
      addWrappedText("✅ Recommended Actions", 16, true);
      data.actions.forEach((action, index) => {
        addWrappedText(`${index + 1}. ${action}`, 11);
      });
    }

    // Footer
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`Page ${i} of ${pageCount} | Generated by SheetSage.ai`, margin, 290);
    }

    // Save PDF
    const pdfFileName = fileName.replace(/\.[^/.]+$/, "") + "_analysis.pdf";
    pdf.save(pdfFileName);

    toast({
      title: "PDF downloaded!",
      description: `Your analysis report has been saved as ${pdfFileName}`,
    });
  };

  return (
    <section className="py-16 bg-gradient-subtle min-h-screen">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="max-w-4xl mx-auto mb-8 animate-fade-in">
          <div className="flex items-center justify-between flex-wrap gap-4 mb-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-hero flex items-center justify-center">
                <FileSpreadsheet className="w-5 h-5 text-primary-foreground" />
              </div>
              <div>
                <h1 className="font-display font-bold text-2xl">Analysis Complete</h1>
                <p className="text-sm text-muted-foreground">{fileName}</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Button 
                variant={canDownload ? "default" : "outline"} 
                onClick={handleDownloadPDF}
                className="gap-2"
              >
                {canDownload ? (
                  <>
                    <Download className="w-4 h-4" />
                    Download PDF
                  </>
                ) : (
                  <>
                    <Lock className="w-4 h-4" />
                    PDF (Pro)
                  </>
                )}
              </Button>
              <Button variant="outline" onClick={onNewAnalysis}>
                Analyze Another File
              </Button>
            </div>
          </div>

          {/* Quick Stats */}
          <div className="grid grid-cols-3 gap-4 mb-8">
            <StatCard label="Rows" value={data.stats.rows.toLocaleString()} icon={<TrendingUp className="w-4 h-4" />} delay={0} />
            <StatCard label="Columns" value={data.stats.columns.toString()} icon={<FileSpreadsheet className="w-4 h-4" />} delay={100} />
            <StatCard 
              label="Issues Found" 
              value={data.stats.issues.toString()} 
              icon={<AlertTriangle className="w-4 h-4" />}
              variant={data.stats.issues > 0 ? 'warning' : 'success'}
              delay={200}
            />
          </div>
        </div>

        {/* Analysis Sections */}
        <div className="max-w-4xl mx-auto space-y-6">
          {/* Summary */}
          <AnalysisCard
            icon={<FileSpreadsheet className="w-5 h-5" />}
            title="📌 Summary"
            variant="default"
            delay={300}
          >
            <p className="text-muted-foreground mb-2">{data.datasetInfo}</p>
            <p className="font-medium">{data.summary}</p>
          </AnalysisCard>

          {/* Key Insights */}
          <AnalysisCard
            icon={<Lightbulb className="w-5 h-5" />}
            title="🔍 Key Insights"
            variant="insight"
            delay={400}
          >
            <ul className="space-y-3">
              {data.insights.map((insight, index) => (
                <li key={index} className="flex items-start gap-3 transition-all duration-200 hover:translate-x-1">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary shrink-0" />
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          </AnalysisCard>

          {/* Warnings */}
          {data.warnings.length > 0 && (
            <AnalysisCard
              icon={<AlertTriangle className="w-5 h-5" />}
              title="⚠️ Warnings / Risks"
              variant="warning"
              delay={500}
            >
              <ul className="space-y-3">
                {data.warnings.map((warning, index) => (
                  <li key={index} className="flex items-start gap-3 transition-all duration-200 hover:translate-x-1">
                    <span className={`mt-1.5 w-1.5 h-1.5 rounded-full shrink-0 ${
                      warning.severity === 'high' ? 'bg-destructive' :
                      warning.severity === 'medium' ? 'bg-warning' : 'bg-muted-foreground'
                    }`} />
                    <span>{warning.text}</span>
                  </li>
                ))}
              </ul>
            </AnalysisCard>
          )}

          {/* Opportunities */}
          <AnalysisCard
            icon={<Rocket className="w-5 h-5" />}
            title="🚀 Opportunities"
            variant="opportunity"
            delay={600}
          >
            <ul className="space-y-3">
              {data.opportunities.map((opportunity, index) => (
                <li key={index} className="flex items-start gap-3 transition-all duration-200 hover:translate-x-1">
                  <TrendingUp className="w-4 h-4 mt-0.5 text-success shrink-0" />
                  <span>{opportunity}</span>
                </li>
              ))}
            </ul>
          </AnalysisCard>

          {/* Recommended Actions */}
          <AnalysisCard
            icon={<CheckCircle2 className="w-5 h-5" />}
            title="✅ Recommended Actions"
            variant="action"
            delay={700}
          >
            <ul className="space-y-4">
              {data.actions.map((action, index) => (
                <li key={index} className="flex items-start gap-3 p-3 rounded-lg bg-secondary/50 transition-all duration-200 hover:bg-secondary hover:translate-x-1">
                  <span className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold shrink-0">
                    {index + 1}
                  </span>
                  <div className="flex-1">
                    <span className="font-medium">{action}</span>
                  </div>
                  <ArrowRight className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" />
                </li>
              ))}
            </ul>
          </AnalysisCard>
        </div>

        {/* Upgrade CTA for Free users */}
        {!canDownload && (
          <div className="max-w-4xl mx-auto mt-8 animate-fade-in" style={{ animationDelay: '800ms' }}>
            <div className="bg-gradient-hero rounded-2xl p-6 text-center text-primary-foreground">
              <h3 className="font-display font-bold text-lg mb-2">Unlock PDF Downloads</h3>
              <p className="text-primary-foreground/80 mb-4">
                Upgrade to Pro or Business to download your analysis reports as PDF files.
              </p>
              <Button variant="secondary" className="bg-white text-primary hover:bg-white/90">
                Upgrade Now
              </Button>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

const StatCard = ({ 
  label, 
  value, 
  icon,
  variant = 'default',
  delay = 0
}: { 
  label: string; 
  value: string; 
  icon: React.ReactNode;
  variant?: 'default' | 'warning' | 'success';
  delay?: number;
}) => (
  <div 
    className="bg-card border border-border rounded-xl p-4 shadow-soft animate-fade-in transition-all duration-300 hover:shadow-medium hover:scale-[1.02]"
    style={{ animationDelay: `${delay}ms` }}
  >
    <div className="flex items-center gap-2 mb-2">
      <span className={
        variant === 'warning' ? 'text-warning' :
        variant === 'success' ? 'text-success' : 'text-primary'
      }>
        {icon}
      </span>
      <span className="text-sm text-muted-foreground">{label}</span>
    </div>
    <p className="font-display font-bold text-2xl">{value}</p>
  </div>
);

const AnalysisCard = ({ 
  icon, 
  title, 
  children,
  variant = 'default',
  delay = 0
}: { 
  icon: React.ReactNode; 
  title: string; 
  children: React.ReactNode;
  variant?: 'default' | 'insight' | 'warning' | 'opportunity' | 'action';
  delay?: number;
}) => {
  const borderColors = {
    default: 'border-border',
    insight: 'border-l-4 border-l-primary border-border',
    warning: 'border-l-4 border-l-warning border-border',
    opportunity: 'border-l-4 border-l-opportunity border-border',
    action: 'border-l-4 border-l-success border-border',
  };

  return (
    <div 
      className={`bg-card rounded-xl p-6 shadow-soft border animate-fade-in transition-all duration-300 hover:shadow-medium ${borderColors[variant]}`}
      style={{ animationDelay: `${delay}ms` }}
    >
      <div className="flex items-center gap-3 mb-4">
        <span className="text-primary">{icon}</span>
        <h2 className="font-display font-semibold text-lg">{title}</h2>
      </div>
      {children}
    </div>
  );
};

export default AnalysisResult;
