import { useState } from "react";
import {
  FileSpreadsheet,
  Lightbulb,
  AlertTriangle,
  Rocket,
  CheckCircle2,
  TrendingUp,
  ArrowRight,
  Download,
  Lock,
  Database,
  Wrench,
  BarChart3,
  Brain,
  Target,
  ChevronDown,
  ChevronUp,
  Activity,
  Zap,
  Shield,
  Gauge,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { Link } from "react-router-dom";
import jsPDF from "jspdf";
import { DataScienceAnalysis } from "@/types/dataScienceAnalysis";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";

interface EnhancedAnalysisResultProps {
  data: DataScienceAnalysis;
  fileName: string;
  onNewAnalysis: () => void;
  userPlan?: string;
}

const EnhancedAnalysisResult = ({
  data,
  fileName,
  onNewAnalysis,
  userPlan = "free",
}: EnhancedAnalysisResultProps) => {
  const { toast } = useToast();
  const canDownload = userPlan === "pro" || userPlan === "business";
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(["summary"]));

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  const handleDownloadPDF = () => {
    if (!canDownload) {
      toast({
        title: "Upgrade required",
        description: "PDF export is available for Pro and Business plans.",
        variant: "destructive",
      });
      return;
    }

    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = 20;

    const addWrappedText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
      pdf.setFontSize(fontSize);
      pdf.setFont("helvetica", isBold ? "bold" : "normal");
      const lines = pdf.splitTextToSize(text, maxWidth);
      
      lines.forEach((line: string) => {
        if (yPosition > 270) {
          pdf.addPage();
          yPosition = 20;
        }
        pdf.text(line, margin, yPosition);
        yPosition += fontSize * 0.5;
      });
      yPosition += 5;
    };

    // Title
    pdf.setFillColor(59, 130, 246);
    pdf.rect(0, 0, pageWidth, 40, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont("helvetica", "bold");
    pdf.text("SheetSage Data Science Report", margin, 28);
    
    yPosition = 50;
    pdf.setTextColor(0, 0, 0);

    addWrappedText(`File: ${fileName}`, 14, true);
    addWrappedText(`Generated: ${new Date().toLocaleDateString()}`, 10);
    yPosition += 5;

    // Executive Summary
    addWrappedText("Executive Summary", 16, true);
    addWrappedText(data.executiveSummary.headline, 11);
    addWrappedText(`Confidence: ${data.executiveSummary.confidenceLevel}`, 10);
    yPosition += 5;

    // Key Findings
    addWrappedText("Key Findings", 14, true);
    data.executiveSummary.keyFindings.forEach((finding, index) => {
      addWrappedText(`${index + 1}. ${finding}`, 11);
    });
    yPosition += 5;

    // Data Health
    addWrappedText("Data Health Report", 14, true);
    addWrappedText(`Quality: ${data.dataHealth.dataQuality} (${data.dataHealth.dataQualityScore}/100)`, 11);
    addWrappedText(`Rows: ${data.dataHealth.totalRows} | Columns: ${data.dataHealth.totalColumns}`, 11);
    addWrappedText(`Duplicates: ${data.dataHealth.duplicateRows} | Outliers: ${data.dataHealth.outlierCount}`, 11);
    yPosition += 5;

    // ML Recommendations
    addWrappedText("ML Model Recommendations", 14, true);
    addWrappedText(`Best Model: ${data.mlRecommendations.bestModel}`, 11, true);
    data.mlRecommendations.recommendedModels.forEach((model) => {
      addWrappedText(`${model.modelName}: ${model.justification}`, 11);
    });
    yPosition += 5;

    // Business Recommendations
    addWrappedText("Business Recommendations", 14, true);
    data.finalInsights.businessRecommendations.forEach((rec, index) => {
      addWrappedText(`${index + 1}. ${rec.action}`, 11);
      addWrappedText(`   Impact: ${rec.impact} | Effort: ${rec.effort}`, 10);
    });

    // Footer
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`Page ${i} of ${pageCount} | Generated by SheetSage.ai`, margin, 290);
    }

    const pdfFileName = fileName.replace(/\.[^/.]+$/, "") + "_ds_analysis.pdf";
    pdf.save(pdfFileName);

    toast({
      title: "PDF downloaded!",
      description: `Your data science report has been saved as ${pdfFileName}`,
    });
  };

  const getQualityColor = (quality: string) => {
    switch (quality) {
      case "Excellent": return "text-success";
      case "Good": return "text-primary";
      case "Fair": return "text-warning";
      case "Poor": return "text-destructive";
      default: return "text-muted-foreground";
    }
  };

  const getSeverityBadge = (severity: string) => {
    switch (severity) {
      case "high": return <Badge variant="destructive">High</Badge>;
      case "medium": return <Badge variant="outline" className="border-warning text-warning">Medium</Badge>;
      case "low": return <Badge variant="secondary">Low</Badge>;
      default: return null;
    }
  };

  return (
    <section className="py-16 bg-gradient-subtle min-h-screen">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="max-w-5xl mx-auto mb-8 animate-fade-in">
          <div className="flex items-center justify-between flex-wrap gap-4 mb-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-gradient-hero flex items-center justify-center">
                <Brain className="w-6 h-6 text-primary-foreground" />
              </div>
              <div>
                <h1 className="font-display font-bold text-2xl">Data Science Analysis Complete</h1>
                <p className="text-sm text-muted-foreground">{fileName}</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Button
                variant={canDownload ? "default" : "outline"}
                onClick={handleDownloadPDF}
                className="gap-2"
              >
                {canDownload ? (
                  <>
                    <Download className="w-4 h-4" />
                    Download PDF
                  </>
                ) : (
                  <>
                    <Lock className="w-4 h-4" />
                    PDF (Pro)
                  </>
                )}
              </Button>
              <Button variant="outline" onClick={onNewAnalysis}>
                Analyze Another File
              </Button>
            </div>
          </div>

          {/* Confidence Badge */}
          <div className="flex items-center gap-2 mb-4">
            <Gauge className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm text-muted-foreground">Analysis Confidence:</span>
            <Badge variant={
              data.executiveSummary.confidenceLevel === "high" ? "default" :
              data.executiveSummary.confidenceLevel === "medium" ? "outline" : "secondary"
            }>
              {data.executiveSummary.confidenceLevel.charAt(0).toUpperCase() + data.executiveSummary.confidenceLevel.slice(1)}
            </Badge>
          </div>

          {/* Quick Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            <QuickStatCard
              label="Data Quality"
              value={data.dataHealth.dataQuality}
              subValue={`${data.dataHealth.dataQualityScore}/100`}
              icon={<Activity className="w-4 h-4" />}
              valueClass={getQualityColor(data.dataHealth.dataQuality)}
            />
            <QuickStatCard
              label="Rows × Columns"
              value={`${data.dataHealth.totalRows.toLocaleString()}`}
              subValue={`× ${data.dataHealth.totalColumns} cols`}
              icon={<Database className="w-4 h-4" />}
            />
            <QuickStatCard
              label="Best Model"
              value={data.mlRecommendations.bestModel}
              subValue={data.mlRecommendations.inferredGoal}
              icon={<Brain className="w-4 h-4" />}
            />
            <QuickStatCard
              label="Issues Found"
              value={(data.dataHealth.missingValues.length + data.dataHealth.duplicateRows).toString()}
              subValue={`${data.dataHealth.outlierCount} outliers`}
              icon={<AlertTriangle className="w-4 h-4" />}
              valueClass={data.dataHealth.duplicateRows > 0 ? "text-warning" : "text-success"}
            />
          </div>
        </div>

        {/* Main Content with Tabs */}
        <div className="max-w-5xl mx-auto">
          <Tabs defaultValue="summary" className="space-y-6">
            <TabsList className="grid w-full grid-cols-3 md:grid-cols-6 gap-1">
              <TabsTrigger value="summary" className="text-xs md:text-sm">Summary</TabsTrigger>
              <TabsTrigger value="data-health" className="text-xs md:text-sm">Data Health</TabsTrigger>
              <TabsTrigger value="eda" className="text-xs md:text-sm">EDA</TabsTrigger>
              <TabsTrigger value="ml-models" className="text-xs md:text-sm">ML Models</TabsTrigger>
              <TabsTrigger value="performance" className="text-xs md:text-sm">Performance</TabsTrigger>
              <TabsTrigger value="recommendations" className="text-xs md:text-sm">Actions</TabsTrigger>
            </TabsList>

            {/* Executive Summary Tab */}
            <TabsContent value="summary" className="space-y-6">
              <AnalysisCard
                icon={<Target className="w-5 h-5" />}
                title="Executive Summary"
                variant="default"
              >
                <p className="text-lg font-medium mb-4">{data.executiveSummary.headline}</p>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-semibold text-sm text-muted-foreground mb-2">Key Findings</h4>
                    <ul className="space-y-2">
                      {data.executiveSummary.keyFindings.map((finding, index) => (
                        <li key={index} className="flex items-start gap-3">
                          <Zap className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                          <span>{finding}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className="p-4 bg-secondary/50 rounded-lg">
                    <h4 className="font-semibold text-sm mb-2">Bottom Line</h4>
                    <p>{data.executiveSummary.bottomLine}</p>
                  </div>
                </div>
              </AnalysisCard>
            </TabsContent>

            {/* Data Health Tab */}
            <TabsContent value="data-health" className="space-y-6">
              <AnalysisCard
                icon={<Database className="w-5 h-5" />}
                title="Data Health Report"
                variant="insight"
              >
                <div className="grid gap-6">
                  {/* Quality Score */}
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium">Data Quality Score</span>
                      <span className={`font-bold ${getQualityColor(data.dataHealth.dataQuality)}`}>
                        {data.dataHealth.dataQualityScore}/100
                      </span>
                    </div>
                    <Progress value={data.dataHealth.dataQualityScore} className="h-3" />
                  </div>

                  {/* Stats Grid */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <StatBox label="Duplicate Rows" value={data.dataHealth.duplicateRows} />
                    <StatBox label="Outliers" value={data.dataHealth.outlierCount} />
                    <StatBox label="Leakage Risk" value={data.dataHealth.dataLeakageRisk} />
                    <StatBox label="Missing Cols" value={data.dataHealth.missingValues.length} />
                  </div>

                  {/* Column Types */}
                  <div>
                    <h4 className="font-semibold text-sm mb-3">Column Analysis</h4>
                    <div className="overflow-x-auto">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="border-b border-border">
                            <th className="text-left py-2 font-medium">Column</th>
                            <th className="text-left py-2 font-medium">Type</th>
                            <th className="text-left py-2 font-medium">Role</th>
                            <th className="text-left py-2 font-medium">Nulls</th>
                          </tr>
                        </thead>
                        <tbody>
                          {data.dataHealth.columnTypes.slice(0, 10).map((col, index) => (
                            <tr key={index} className="border-b border-border/50">
                              <td className="py-2 font-mono text-xs">{col.name}</td>
                              <td className="py-2">
                                <Badge variant="outline" className="text-xs">{col.type}</Badge>
                              </td>
                              <td className="py-2">
                                <Badge variant={col.potentialRole === "target" ? "default" : "secondary"} className="text-xs">
                                  {col.potentialRole}
                                </Badge>
                              </td>
                              <td className="py-2">{col.nullPercentage.toFixed(1)}%</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>

                  {/* Missing Values */}
                  {data.dataHealth.missingValues.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-sm mb-3">Missing Value Strategies</h4>
                      <div className="space-y-2">
                        {data.dataHealth.missingValues.map((mv, index) => (
                          <div key={index} className="flex items-center justify-between p-3 bg-secondary/30 rounded-lg">
                            <div>
                              <span className="font-mono text-sm">{mv.column}</span>
                              <span className="text-muted-foreground text-sm ml-2">
                                ({mv.missingPercentage.toFixed(1)}% missing)
                              </span>
                            </div>
                            <Badge variant="outline">{mv.suggestedStrategy}</Badge>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </AnalysisCard>

              {/* Data Preparation */}
              <AnalysisCard
                icon={<Wrench className="w-5 h-5" />}
                title="Data Preparation Steps"
                variant="action"
              >
                <div className="space-y-4">
                  {data.dataPreparation.cleaningSteps.map((step, index) => (
                    <div key={index} className="flex items-start gap-4 p-3 rounded-lg bg-secondary/30">
                      <span className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold shrink-0">
                        {step.step}
                      </span>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="font-medium">{step.action}</span>
                          {getSeverityBadge(step.impact)}
                        </div>
                        <p className="text-sm text-muted-foreground">{step.reason}</p>
                      </div>
                    </div>
                  ))}
                  
                  <div className="grid md:grid-cols-2 gap-4 mt-4">
                    <div className="p-4 bg-secondary/30 rounded-lg">
                      <h5 className="font-medium text-sm mb-2">Encoding Strategy</h5>
                      <p className="text-sm text-muted-foreground">
                        Categorical: {data.dataPreparation.encodingStrategy.categorical}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        Text: {data.dataPreparation.encodingStrategy.text}
                      </p>
                    </div>
                    <div className="p-4 bg-secondary/30 rounded-lg">
                      <h5 className="font-medium text-sm mb-2">Scaling Method</h5>
                      <p className="text-sm">{data.dataPreparation.scalingMethod}</p>
                    </div>
                  </div>

                  {data.dataPreparation.featureEngineering.length > 0 && (
                    <div className="p-4 bg-primary/5 rounded-lg border border-primary/20">
                      <h5 className="font-medium text-sm mb-2">Feature Engineering Suggestions</h5>
                      <ul className="space-y-1">
                        {data.dataPreparation.featureEngineering.map((fe, index) => (
                          <li key={index} className="text-sm flex items-start gap-2">
                            <Lightbulb className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                            {fe}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </AnalysisCard>
            </TabsContent>

            {/* EDA Tab */}
            <TabsContent value="eda" className="space-y-6">
              <AnalysisCard
                icon={<BarChart3 className="w-5 h-5" />}
                title="Exploratory Data Analysis"
                variant="insight"
              >
                <p className="text-muted-foreground mb-6">{data.edaInsights.statisticalSummary}</p>

                <div className="space-y-4">
                  {data.edaInsights.insights.map((insight, index) => (
                    <div
                      key={index}
                      className={`p-4 rounded-lg border-l-4 ${
                        insight.importance === "high"
                          ? "border-l-primary bg-primary/5"
                          : insight.importance === "medium"
                          ? "border-l-warning bg-warning/5"
                          : "border-l-muted bg-muted/5"
                      }`}
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <Badge variant="outline" className="text-xs">{insight.category}</Badge>
                        {getSeverityBadge(insight.importance)}
                      </div>
                      <h5 className="font-semibold mb-1">{insight.title}</h5>
                      <p className="text-sm text-muted-foreground">{insight.description}</p>
                      {insight.technicalDetails && (
                        <p className="text-xs text-muted-foreground mt-2 font-mono">
                          {insight.technicalDetails}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </AnalysisCard>

              {/* Correlations */}
              {data.edaInsights.topCorrelations.length > 0 && (
                <AnalysisCard
                  icon={<TrendingUp className="w-5 h-5" />}
                  title="Top Correlations"
                  variant="default"
                >
                  <div className="space-y-3">
                    {data.edaInsights.topCorrelations.map((corr, index) => (
                      <div key={index} className="flex items-center justify-between p-3 bg-secondary/30 rounded-lg">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-sm">{corr.feature1}</span>
                          <ArrowRight className="w-4 h-4 text-muted-foreground" />
                          <span className="font-mono text-sm">{corr.feature2}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge variant={corr.strength === "strong" ? "default" : "outline"}>
                            {corr.correlationValue.toFixed(2)}
                          </Badge>
                          <span className={`text-xs ${corr.direction === "positive" ? "text-success" : "text-destructive"}`}>
                            {corr.direction}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </AnalysisCard>
              )}

              {/* Feature Importance */}
              {data.edaInsights.featureImportance.length > 0 && (
                <AnalysisCard
                  icon={<Zap className="w-5 h-5" />}
                  title="Feature Importance"
                  variant="opportunity"
                >
                  <div className="space-y-3">
                    {data.edaInsights.featureImportance.map((fi, index) => (
                      <div key={index}>
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-mono text-sm">{fi.feature}</span>
                          <span className="text-sm font-medium">{(fi.importance * 100).toFixed(1)}%</span>
                        </div>
                        <Progress value={fi.importance * 100} className="h-2 mb-1" />
                        <p className="text-xs text-muted-foreground">{fi.reason}</p>
                      </div>
                    ))}
                  </div>
                </AnalysisCard>
              )}
            </TabsContent>

            {/* ML Models Tab */}
            <TabsContent value="ml-models" className="space-y-6">
              <AnalysisCard
                icon={<Brain className="w-5 h-5" />}
                title="ML Model Recommendations"
                variant="insight"
              >
                <div className="flex items-center gap-4 mb-6 p-4 bg-primary/10 rounded-lg">
                  <div>
                    <p className="text-sm text-muted-foreground">Inferred Goal</p>
                    <p className="font-semibold">{data.mlRecommendations.inferredGoal}</p>
                  </div>
                  {data.mlRecommendations.targetVariable && (
                    <div className="border-l border-border pl-4">
                      <p className="text-sm text-muted-foreground">Target Variable</p>
                      <p className="font-mono">{data.mlRecommendations.targetVariable}</p>
                    </div>
                  )}
                </div>

                <div className="space-y-6">
                  {data.mlRecommendations.recommendedModels.map((model, index) => (
                    <div
                      key={index}
                      className={`p-5 rounded-xl border ${
                        model.modelName === data.mlRecommendations.bestModel
                          ? "border-primary bg-primary/5"
                          : "border-border"
                      }`}
                    >
                      <div className="flex items-start justify-between mb-4">
                        <div>
                          <div className="flex items-center gap-2 mb-1">
                            <h4 className="font-semibold text-lg">{model.modelName}</h4>
                            {model.modelName === data.mlRecommendations.bestModel && (
                              <Badge className="bg-primary">Recommended</Badge>
                            )}
                          </div>
                          <p className="text-sm text-muted-foreground">{model.modelType}</p>
                        </div>
                        <div className="text-right">
                          <div className="text-2xl font-bold text-primary">{model.suitabilityScore}%</div>
                          <p className="text-xs text-muted-foreground">Suitability</p>
                        </div>
                      </div>

                      <p className="text-sm mb-4">{model.justification}</p>

                      <div className="grid md:grid-cols-3 gap-4 mb-4">
                        <div className="p-3 bg-secondary/30 rounded-lg">
                          <p className="text-xs text-muted-foreground mb-1">Interpretability</p>
                          <Badge variant="outline">{model.interpretability}</Badge>
                        </div>
                        <div className="p-3 bg-secondary/30 rounded-lg">
                          <p className="text-xs text-muted-foreground mb-1">Training Complexity</p>
                          <Badge variant="outline">{model.trainingComplexity}</Badge>
                        </div>
                        <div className="p-3 bg-secondary/30 rounded-lg">
                          <p className="text-xs text-muted-foreground mb-1">Expected Performance</p>
                          <p className="text-sm">{model.expectedPerformance}</p>
                        </div>
                      </div>

                      <div className="grid md:grid-cols-2 gap-4">
                        <div>
                          <h5 className="text-sm font-medium text-success mb-2">Pros</h5>
                          <ul className="space-y-1">
                            {model.pros.map((pro, i) => (
                              <li key={i} className="text-sm flex items-start gap-2">
                                <CheckCircle2 className="w-4 h-4 text-success mt-0.5 shrink-0" />
                                {pro}
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <h5 className="text-sm font-medium text-destructive mb-2">Cons</h5>
                          <ul className="space-y-1">
                            {model.cons.map((con, i) => (
                              <li key={i} className="text-sm flex items-start gap-2">
                                <AlertTriangle className="w-4 h-4 text-destructive mt-0.5 shrink-0" />
                                {con}
                              </li>
                            ))}
                          </ul>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                {data.mlRecommendations.alternativeApproaches.length > 0 && (
                  <div className="mt-6 p-4 bg-secondary/30 rounded-lg">
                    <h4 className="font-medium mb-2">Alternative Approaches</h4>
                    <ul className="space-y-1">
                      {data.mlRecommendations.alternativeApproaches.map((approach, index) => (
                        <li key={index} className="text-sm text-muted-foreground">
                          • {approach}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </AnalysisCard>
            </TabsContent>

            {/* Performance Tab */}
            <TabsContent value="performance" className="space-y-6">
              <AnalysisCard
                icon={<Activity className="w-5 h-5" />}
                title="Model Performance Comparison"
                variant="default"
              >
                <div className="space-y-4">
                  {data.modelPerformance.performanceComparison.map((perf, index) => (
                    <div
                      key={index}
                      className={`p-4 rounded-lg border ${
                        perf.isRecommended ? "border-primary bg-primary/5" : "border-border"
                      }`}
                    >
                      <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center gap-2">
                          <span className="w-6 h-6 rounded-full bg-secondary flex items-center justify-center text-sm font-bold">
                            {perf.rank}
                          </span>
                          <span className="font-semibold">{perf.modelName}</span>
                          {perf.isRecommended && <Badge>Best</Badge>}
                        </div>
                      </div>
                      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                        {perf.metrics.map((metric, mIndex) => (
                          <div key={mIndex} className="p-2 bg-secondary/30 rounded">
                            <p className="text-xs text-muted-foreground">{metric.name}</p>
                            <p className="font-mono font-medium">{metric.value.toFixed(4)}</p>
                          </div>
                        ))}
                      </div>
                      {perf.notes && (
                        <p className="text-sm text-muted-foreground mt-2">{perf.notes}</p>
                      )}
                    </div>
                  ))}
                </div>
              </AnalysisCard>

              <AnalysisCard
                icon={<Target className="w-5 h-5" />}
                title="Best Model Details"
                variant="action"
              >
                <h3 className="text-xl font-semibold mb-2">
                  {data.modelPerformance.bestModelDetails.name}
                </h3>
                <p className="text-muted-foreground mb-4">
                  {data.modelPerformance.bestModelDetails.whyBest}
                </p>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  {data.modelPerformance.bestModelDetails.keyMetrics.map((metric, index) => (
                    <div key={index} className="p-4 bg-primary/10 rounded-lg text-center">
                      <p className="text-sm text-muted-foreground mb-1">{metric.name}</p>
                      <p className="text-2xl font-bold text-primary">{metric.value.toFixed(4)}</p>
                      <p className="text-xs text-muted-foreground mt-1">{metric.interpretation}</p>
                    </div>
                  ))}
                </div>
              </AnalysisCard>
            </TabsContent>

            {/* Recommendations Tab */}
            <TabsContent value="recommendations" className="space-y-6">
              {/* Key Drivers */}
              <AnalysisCard
                icon={<Zap className="w-5 h-5" />}
                title="Key Drivers"
                variant="insight"
              >
                <ul className="space-y-2">
                  {data.finalInsights.keyDrivers.map((driver, index) => (
                    <li key={index} className="flex items-start gap-3">
                      <TrendingUp className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                      <span>{driver}</span>
                    </li>
                  ))}
                </ul>
              </AnalysisCard>

              {/* Business Recommendations */}
              <AnalysisCard
                icon={<Rocket className="w-5 h-5" />}
                title="Business Recommendations"
                variant="opportunity"
              >
                <div className="space-y-4">
                  {data.finalInsights.businessRecommendations.map((rec, index) => (
                    <div key={index} className="p-4 rounded-lg bg-secondary/30 border-l-4 border-l-success">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <span className="w-6 h-6 rounded-full bg-success text-success-foreground flex items-center justify-center text-sm font-bold">
                            {rec.priority}
                          </span>
                          <span className="font-semibold">{rec.action}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge variant="outline">Impact: {rec.impact}</Badge>
                          <Badge variant="outline">Effort: {rec.effort}</Badge>
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">{rec.rationale}</p>
                      <p className="text-sm font-medium text-success">Expected: {rec.expectedOutcome}</p>
                    </div>
                  ))}
                </div>
              </AnalysisCard>

              {/* Risks & Limitations */}
              <AnalysisCard
                icon={<Shield className="w-5 h-5" />}
                title="Risks & Limitations"
                variant="warning"
              >
                <div className="space-y-3">
                  {data.finalInsights.risksAndLimitations.map((risk, index) => (
                    <div key={index} className="p-4 rounded-lg bg-destructive/5 border border-destructive/20">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge variant="outline" className="text-xs">{risk.type}</Badge>
                        {getSeverityBadge(risk.severity)}
                      </div>
                      <p className="font-medium mb-1">{risk.description}</p>
                      <p className="text-sm text-muted-foreground">
                        <strong>Mitigation:</strong> {risk.mitigation}
                      </p>
                    </div>
                  ))}
                </div>
              </AnalysisCard>

              {/* Next Steps */}
              <AnalysisCard
                icon={<CheckCircle2 className="w-5 h-5" />}
                title="Next Steps"
                variant="action"
              >
                <div className="space-y-3">
                  {data.finalInsights.nextSteps.map((step, index) => (
                    <div
                      key={index}
                      className="flex items-center gap-4 p-3 rounded-lg bg-secondary/30 hover:bg-secondary/50 transition-colors"
                    >
                      <span className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold shrink-0">
                        {step.priority}
                      </span>
                      <div className="flex-1">
                        <p className="font-medium">{step.step}</p>
                        <div className="flex items-center gap-2 mt-1">
                          <Badge variant="outline" className="text-xs">{step.category}</Badge>
                          <Badge variant="secondary" className="text-xs">Effort: {step.effort}</Badge>
                        </div>
                      </div>
                      <ArrowRight className="w-4 h-4 text-muted-foreground" />
                    </div>
                  ))}
                </div>
              </AnalysisCard>
            </TabsContent>
          </Tabs>
        </div>

        {/* Upgrade CTA for Free users */}
        {!canDownload && (
          <div className="max-w-5xl mx-auto mt-8 animate-fade-in">
            <div className="bg-gradient-hero rounded-2xl p-6 text-center text-primary-foreground">
              <h3 className="font-display font-bold text-lg mb-2">Unlock Full Reports</h3>
              <p className="text-primary-foreground/80 mb-4">
                Upgrade to Pro or Business to download comprehensive PDF reports.
              </p>
              <Link to="/#pricing">
                <Button variant="secondary" className="bg-white text-primary hover:bg-white/90">
                  Upgrade Now
                </Button>
              </Link>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

// Helper Components
const QuickStatCard = ({
  label,
  value,
  subValue,
  icon,
  valueClass = "",
}: {
  label: string;
  value: string;
  subValue?: string;
  icon: React.ReactNode;
  valueClass?: string;
}) => (
  <div className="bg-card border border-border rounded-xl p-4 shadow-soft">
    <div className="flex items-center gap-2 mb-2">
      <span className="text-primary">{icon}</span>
      <span className="text-sm text-muted-foreground">{label}</span>
    </div>
    <p className={`font-display font-bold text-xl ${valueClass}`}>{value}</p>
    {subValue && <p className="text-xs text-muted-foreground">{subValue}</p>}
  </div>
);

const StatBox = ({ label, value }: { label: string; value: string | number }) => (
  <div className="p-3 bg-secondary/30 rounded-lg text-center">
    <p className="text-xs text-muted-foreground mb-1">{label}</p>
    <p className="font-semibold">{value}</p>
  </div>
);

const AnalysisCard = ({
  icon,
  title,
  children,
  variant = "default",
}: {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
  variant?: "default" | "insight" | "warning" | "opportunity" | "action";
}) => {
  const borderColors = {
    default: "border-border",
    insight: "border-l-4 border-l-primary border-border",
    warning: "border-l-4 border-l-warning border-border",
    opportunity: "border-l-4 border-l-opportunity border-border",
    action: "border-l-4 border-l-success border-border",
  };

  return (
    <div className={`bg-card rounded-xl p-6 shadow-soft border transition-all duration-300 hover:shadow-medium ${borderColors[variant]}`}>
      <div className="flex items-center gap-3 mb-4">
        <span className="text-primary">{icon}</span>
        <h2 className="font-display font-semibold text-lg">{title}</h2>
      </div>
      {children}
    </div>
  );
};

export default EnhancedAnalysisResult;
